//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Office.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Office;

public class CaseStatus implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public int caseId;

    public CaseStatusEnum status;

    public CaseStatus()
    {
        this.status = CaseStatusEnum.REJECTED;
    }

    public CaseStatus(int caseId, CaseStatusEnum status)
    {
        this.caseId = caseId;
        this.status = status;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CaseStatus r = null;
        if(rhs instanceof CaseStatus)
        {
            r = (CaseStatus)rhs;
        }

        if(r != null)
        {
            if(this.caseId != r.caseId)
            {
                return false;
            }
            if(this.status != r.status)
            {
                if(this.status == null || r.status == null || !this.status.equals(r.status))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Office::CaseStatus");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, caseId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, status);
        return h_;
    }

    public CaseStatus clone()
    {
        CaseStatus c = null;
        try
        {
            c = (CaseStatus)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.caseId);
        CaseStatusEnum.ice_write(ostr, this.status);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.caseId = istr.readInt();
        this.status = CaseStatusEnum.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CaseStatus v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CaseStatus ice_read(com.zeroc.Ice.InputStream istr)
    {
        CaseStatus v = new CaseStatus();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CaseStatus> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CaseStatus v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CaseStatus> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CaseStatus.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CaseStatus _nullMarshalValue = new CaseStatus();

    /** @hidden */
    public static final long serialVersionUID = 3996192375774762790L;
}
