//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Office.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Office;

public interface OfficeRegistrationPrx extends com.zeroc.Ice.ObjectPrx
{
    default int startPassportCase(PassportCaseData passportCaseData)
    {
        return startPassportCase(passportCaseData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int startPassportCase(PassportCaseData passportCaseData, java.util.Map<String, String> context)
    {
        return _iceI_startPassportCaseAsync(passportCaseData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> startPassportCaseAsync(PassportCaseData passportCaseData)
    {
        return _iceI_startPassportCaseAsync(passportCaseData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> startPassportCaseAsync(PassportCaseData passportCaseData, java.util.Map<String, String> context)
    {
        return _iceI_startPassportCaseAsync(passportCaseData, context, false);
    }

    /**
     * @hidden
     * @param iceP_passportCaseData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_startPassportCaseAsync(PassportCaseData iceP_passportCaseData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startPassportCase", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     PassportCaseData.ice_write(ostr, iceP_passportCaseData);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int startVisaCase(VisaCaseData visaCaseData)
    {
        return startVisaCase(visaCaseData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int startVisaCase(VisaCaseData visaCaseData, java.util.Map<String, String> context)
    {
        return _iceI_startVisaCaseAsync(visaCaseData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> startVisaCaseAsync(VisaCaseData visaCaseData)
    {
        return _iceI_startVisaCaseAsync(visaCaseData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> startVisaCaseAsync(VisaCaseData visaCaseData, java.util.Map<String, String> context)
    {
        return _iceI_startVisaCaseAsync(visaCaseData, context, false);
    }

    /**
     * @hidden
     * @param iceP_visaCaseData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_startVisaCaseAsync(VisaCaseData iceP_visaCaseData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startVisaCase", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     VisaCaseData.ice_write(ostr, iceP_visaCaseData);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int startDriverLicenseCase(DriverLicenseCaseData driverLicenseCaseData)
    {
        return startDriverLicenseCase(driverLicenseCaseData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int startDriverLicenseCase(DriverLicenseCaseData driverLicenseCaseData, java.util.Map<String, String> context)
    {
        return _iceI_startDriverLicenseCaseAsync(driverLicenseCaseData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> startDriverLicenseCaseAsync(DriverLicenseCaseData driverLicenseCaseData)
    {
        return _iceI_startDriverLicenseCaseAsync(driverLicenseCaseData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> startDriverLicenseCaseAsync(DriverLicenseCaseData driverLicenseCaseData, java.util.Map<String, String> context)
    {
        return _iceI_startDriverLicenseCaseAsync(driverLicenseCaseData, context, false);
    }

    /**
     * @hidden
     * @param iceP_driverLicenseCaseData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_startDriverLicenseCaseAsync(DriverLicenseCaseData iceP_driverLicenseCaseData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startDriverLicenseCase", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     DriverLicenseCaseData.ice_write(ostr, iceP_driverLicenseCaseData);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default void saveClient(int clientId, ClientPrx client)
    {
        saveClient(clientId, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void saveClient(int clientId, ClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_saveClientAsync(clientId, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> saveClientAsync(int clientId, ClientPrx client)
    {
        return _iceI_saveClientAsync(clientId, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> saveClientAsync(int clientId, ClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_saveClientAsync(clientId, client, context, false);
    }

    /**
     * @hidden
     * @param iceP_clientId -
     * @param iceP_client -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_saveClientAsync(int iceP_clientId, ClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "saveClient", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_clientId);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficeRegistrationPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), OfficeRegistrationPrx.class, _OfficeRegistrationPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficeRegistrationPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), OfficeRegistrationPrx.class, _OfficeRegistrationPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficeRegistrationPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), OfficeRegistrationPrx.class, _OfficeRegistrationPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficeRegistrationPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), OfficeRegistrationPrx.class, _OfficeRegistrationPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static OfficeRegistrationPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, OfficeRegistrationPrx.class, _OfficeRegistrationPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static OfficeRegistrationPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, OfficeRegistrationPrx.class, _OfficeRegistrationPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default OfficeRegistrationPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (OfficeRegistrationPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default OfficeRegistrationPrx ice_adapterId(String newAdapterId)
    {
        return (OfficeRegistrationPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default OfficeRegistrationPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (OfficeRegistrationPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default OfficeRegistrationPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (OfficeRegistrationPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default OfficeRegistrationPrx ice_invocationTimeout(int newTimeout)
    {
        return (OfficeRegistrationPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default OfficeRegistrationPrx ice_connectionCached(boolean newCache)
    {
        return (OfficeRegistrationPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default OfficeRegistrationPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (OfficeRegistrationPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default OfficeRegistrationPrx ice_secure(boolean b)
    {
        return (OfficeRegistrationPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default OfficeRegistrationPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (OfficeRegistrationPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default OfficeRegistrationPrx ice_preferSecure(boolean b)
    {
        return (OfficeRegistrationPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default OfficeRegistrationPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (OfficeRegistrationPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default OfficeRegistrationPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (OfficeRegistrationPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default OfficeRegistrationPrx ice_collocationOptimized(boolean b)
    {
        return (OfficeRegistrationPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default OfficeRegistrationPrx ice_twoway()
    {
        return (OfficeRegistrationPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default OfficeRegistrationPrx ice_oneway()
    {
        return (OfficeRegistrationPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default OfficeRegistrationPrx ice_batchOneway()
    {
        return (OfficeRegistrationPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default OfficeRegistrationPrx ice_datagram()
    {
        return (OfficeRegistrationPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default OfficeRegistrationPrx ice_batchDatagram()
    {
        return (OfficeRegistrationPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default OfficeRegistrationPrx ice_compress(boolean co)
    {
        return (OfficeRegistrationPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default OfficeRegistrationPrx ice_timeout(int t)
    {
        return (OfficeRegistrationPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default OfficeRegistrationPrx ice_connectionId(String connectionId)
    {
        return (OfficeRegistrationPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default OfficeRegistrationPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (OfficeRegistrationPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Office::OfficeRegistration";
    }
}
